// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbmsibgjnvdcflwxsvuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRibXNpYmdqbnZkY2Zsd3hzdnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTIwNTMsImV4cCI6MjA2MjcyODA1M30.ittRJ3e6GSjPRff1_XG1MyjddM17pF9EpXf01sLH_A0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);